import type { AlumniPage, Alum, Department, DepartmentMember, NonEmpty } from "./alumni-types";

// The Alumni page's data. 2021–22 and 2022–23 come from the team's live page
// (politorocketteam.it/about/past-teams, read 2026-10-07) with their groups as
// listed there, and roles tidied as board 28 does: "Lead Engineer" reads
// "Lead", "Mission Analyst - Safety And Launch Manager" reads "Mission
// Analyst · Safety and Launch Manager". The live "Luca Santoto" (2022–23) is
// Luca Santoro, as 2021–22 spells it, and 2021–22's "Ulvi Aydin" is Mustafa
// Ulvi Aydin, as 2022–23 names him. 2024–25 is the Team page's record
// (lib/about/team.ts), grouped by department: each member's department is
// mapped from their role until the dashboard owns it.

/**
 * Stand-in people for a year marked `placeholder: true`, shaped like board
 * 28b's samples. The team replaces them with the real list.
 */
const SAMPLE = "Sample Name";

function samples(leads: number, others: number): NonEmpty<Alum> {
  return [
    { name: SAMPLE, role: "Sample Lead" },
    ...Array.from({ length: leads - 1 }, () => ({ name: SAMPLE, role: "Sample Lead" })),
    ...Array.from({ length: others }, () => ({ name: SAMPLE, role: "Sample Role" })),
  ];
}

function sampleDepartment(department: Department, members: number): NonEmpty<DepartmentMember> {
  return [
    { rank: "head", name: SAMPLE, role: `Head of ${department}`, department },
    { rank: "lead", name: SAMPLE, division: "Sample Division", department },
    { rank: "lead", name: SAMPLE, division: "Sample Division", department },
    ...Array.from({ length: members }, () => ({ rank: "member" as const, name: SAMPLE, role: "Sample Role", department })),
  ];
}

export const alumni: AlumniPage = {
  description:
    "Everyone who has built PoliTo Rocket Team, one academic year at a time, from its founders in 2021–22.",

  header: {
    eyebrow: "ABOUT · ALUMNI",
    title: "Alumni",
    intro: "The people who built the Team, academic year by academic year, from the first one, 2021–22.",
  },

  founders: {
    eyebrow: "WHERE IT STARTED",
    title: "The founders.",
    intro: "Fabio Meloni founded the PoliTo Rocket Team with five co-founders.",
    people: [
      { name: "Fabio Meloni", title: "founder", role: "Founder · President", photo: "/team/fabio-meloni.jpg" },
      { name: "Mattia Saba", title: "co-founder", role: "Mission Analysis" },
      { name: "Salvatore Lagrasta", title: "co-founder", role: "Avionics", photo: "/team/salvatore-lagrasta.jpg" },
      { name: "Andrea Ruscica", title: "co-founder", role: "Recovery" },
      { name: "Cristian Manfredi", title: "co-founder", role: "Liquid Propulsion", photo: "/team/cristian-manfredi.jpg" },
      { name: "Andrea Troglia", title: "co-founder", role: "Recovery" },
    ],
  },

  years: {
    eyebrow: "ACADEMIC YEARS",
    title: "Year by year.",
    list: [
      {
        kind: "departments",
        start: 2025,
        placeholder: true,
        leadership: samples(4, 1),
        members: [
          ...sampleDepartment("Propulsion", 9),
          ...sampleDepartment("Structures", 7),
          ...sampleDepartment("Aerodynamics", 6),
          ...sampleDepartment("Recovery", 4),
          ...sampleDepartment("Controls and Systems", 3),
          ...sampleDepartment("Electronics", 6),
          ...sampleDepartment("Operations", 5),
        ],
        advisors: samples(1, 5),
      },
      {
        kind: "departments",
        start: 2024,
        leadership: [
          { name: "Andrea Pantano", role: "Team Leader" },
          { name: "Andrea Manzo", role: "Chief Engineer" },
          { name: "Riccardo Savio", role: "Project Manager" },
          { name: "Rocco Bellon", role: "Head of Operations" },
          { name: "Marco Dona", role: "Head of R&D" },
        ],
        members: [
          { rank: "head", name: "Marco Delogu", role: "Head of Propulsion", department: "Propulsion" },
          { rank: "lead", name: "Samuele Lombardi", division: "Liquid System Architecture", department: "Propulsion" },
          { rank: "lead", name: "Fabio Zeloni", division: "Thrust Chamber Assembly", department: "Propulsion" },
          { rank: "head", name: "Emir Topakci", role: "Head of Structures", department: "Structures" },
          { rank: "lead", name: "Emir Topakci", division: "Design & Manufacturing", department: "Structures" },
          { rank: "lead", name: "Emir Topakci", division: "Structures Analysis", department: "Structures" },
          { rank: "head", name: "Alessandro Rabino", role: "Head of Aerodynamics", department: "Aerodynamics" },
          { rank: "lead", name: "Maria Angelica Fullone Penna", division: "Mission Analysis", department: "Aerodynamics" },
          { rank: "lead", name: "Stefano Campagnolo", division: "Optimization and Analysis", department: "Aerodynamics" },
          { rank: "head", name: "Daniele Brero", role: "Head of Recovery", department: "Recovery" },
          { rank: "lead", name: "Giovanni Tomasi", division: "Parachutes", department: "Recovery" },
          { rank: "lead", name: "Ludovica Cassella", division: "Recovery Systems", department: "Recovery" },
          { rank: "head", name: "Alessandro Giacobetti", role: "Head of Controls and Systems", department: "Controls and Systems" },
          { rank: "lead", name: "Rocco Donnola", division: "Engine Control System", department: "Controls and Systems" },
          { rank: "lead", name: "Nicola Montagner", division: "Flight Control Systems", department: "Controls and Systems" },
          { rank: "head", name: "Michele Rossetto", role: "Head of Electronics", department: "Electronics" },
          { rank: "lead", name: "Giorgio Montese", division: "Firmware", department: "Electronics" },
          { rank: "lead", name: "Samuele Martello", division: "Ground Station", department: "Electronics" },
          { rank: "lead", name: "Arda Bildik", division: "Hardware", department: "Electronics" },
          { rank: "head", name: "Rocco Bellon", role: "Head of Operations", department: "Operations" },
          { rank: "lead", name: "Luca Beccaria", division: "Communications", department: "Operations" },
          { rank: "lead", name: "Huseyin Gulec", division: "Information Technology", department: "Operations" },
          { rank: "lead", name: "Ettore De Bartolo", division: "Logistics", department: "Operations" },
          { rank: "lead", name: "Asmaa Jamai", division: "Safety", department: "Operations" },
          { rank: "member", name: "Aamil Lodhi", role: "Design & Additive Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Alessandro Centorrino", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Alessandro Monti", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Alessandro Rizzo", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Alessandro Ruo Redda", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Alessio Golini", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Alessio Nerjaku", role: "Mission Analyst", department: "Aerodynamics" },
          { rank: "member", name: "Andrea Agostini", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Andrea Morra", role: "Ignition System Engineer", department: "Propulsion" },
          { rank: "member", name: "Annamaria Gelesz", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Antonino Brandino", role: "Recovery Engineer", department: "Recovery" },
          { rank: "member", name: "Antonino Spadafora", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Antonino Gaetano Biondo", role: "Control Systems Engineer", department: "Controls and Systems" },
          { rank: "member", name: "Antonio Sepe", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Antonios Kakamoukas", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Ata Akturk", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Aurelio Amato", role: "Mission Analyst", department: "Aerodynamics" },
          { rank: "member", name: "Aysim Kukrek", role: "Recovery Engineer", department: "Recovery" },
          { rank: "member", name: "Beatrice La Motta", role: "Test Engineer", department: "Propulsion" },
          { rank: "member", name: "Carlo Paccagnella", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Carlo Ricciardi", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Carlo Visalli", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Chiara Balen", role: "Recovery Engineer", department: "Recovery" },
          { rank: "member", name: "Claudia Sanna", role: "Desktop App Developer", department: "Operations" },
          { rank: "member", name: "Cristiana Avati", role: "Ignition System Engineer", department: "Propulsion" },
          { rank: "member", name: "Cristina Pecoriello", role: "Cryogenic System Engineer", department: "Propulsion" },
          { rank: "member", name: "Daniele Padula", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Daniele Punzi", role: "Recovery Engineer", department: "Recovery" },
          { rank: "member", name: "Daniele Luigi Maresca", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Dante Casaglia", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Davide Adamo", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Davide Di Palmo", role: "Mission Analyst", department: "Aerodynamics" },
          { rank: "member", name: "Dimitri Mazzone", role: "Test Engineer", department: "Propulsion" },
          { rank: "member", name: "Eleonora Catozzo", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Emma Chan", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Enes Göktepe", role: "Mission Analyst", department: "Aerodynamics" },
          { rank: "member", name: "Federico Agricola", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Federico Saviano", role: "Control Systems Engineer", department: "Controls and Systems" },
          { rank: "member", name: "Filippo Prosperi", role: "Test Engineer", department: "Propulsion" },
          { rank: "member", name: "Filippo Pupo", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Flavia Beatrice Anton", role: "Test & Mission Support Specialist", department: "Propulsion" },
          { rank: "member", name: "Flavio Giglia", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Francesco Guerrini", role: "Sponsoring Specialist", department: "Operations" },
          { rank: "member", name: "Francesco Gullo", role: "Recovery Engineer", department: "Recovery" },
          { rank: "member", name: "Francesco Iannantuono", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Gabriel Avila", role: "Feed System Engineer", department: "Propulsion" },
          { rank: "member", name: "Gabriele Angelillo", role: "Embedded Software Engineer", department: "Electronics" },
          { rank: "member", name: "Giacomo Bunino", role: "Control Systems Engineer", department: "Controls and Systems" },
          { rank: "member", name: "Gianluca Marcato", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Gianluca Marra", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Gianluca Paolicelli", role: "RF Specialist", department: "Electronics" },
          { rank: "member", name: "Giuliana Matta", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Harrshit Oruganti Sridhar", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Ilhan Yilmaz Karadeniz", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "İsmail Dündar", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Ismail Emre Karakutuk", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Jenny Rostaing", role: "Valves & Pipelines Engineer", department: "Propulsion" },
          { rank: "member", name: "Lorenzo Assiro", role: "Control Systems Engineer", department: "Controls and Systems" },
          { rank: "member", name: "Lorenzo Scaravaglio", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Luca Pagliei", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Lucas De Jong", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Lucio Ernesto Polci", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Luigi Ruggieri", role: "Ignition System Engineer", department: "Propulsion" },
          { rank: "member", name: "Luisa Barattin", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Marco Mondin", role: "Sponsoring Specialist", department: "Operations" },
          { rank: "member", name: "Margherita Boatto", role: "Test Engineer", department: "Propulsion" },
          { rank: "member", name: "Mariasole Martella", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Martina Ginesi", role: "Aerodynamicist", department: "Aerodynamics" },
          { rank: "member", name: "Matteo Petri", role: "Mechanical/Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Mattia Girotto", role: "Ignition System Engineer", department: "Propulsion" },
          { rank: "member", name: "Mattia Sottile", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Michelangelo Mangiapane", role: "Recovery Engineer", department: "Recovery" },
          { rank: "member", name: "Muhamamd Hamza Khan", role: "Embedded Software Engineer", department: "Electronics" },
          { rank: "member", name: "Mustafa Mert Yetim", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Mustafa Sezer Yilmaz", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Niccolò Faraci", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Nicolas Cerutti", role: "Software Engineer", department: "Operations" },
          { rank: "member", name: "Nicolò Vetri", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Panagiotis Dimitrios Argyris", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Paul Teo Devis", role: "Electronics Engineer", department: "Electronics" },
          { rank: "member", name: "Pietro Isnardi", role: "Mission Analyst", department: "Aerodynamics" },
          { rank: "member", name: "Ricardo Brunetti", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Roberto Moro", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Rocco Maria Cherubini", role: "Mission Analyst", department: "Aerodynamics" },
          { rank: "member", name: "Rosa Coppolino", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Rosario Stramondo", role: "Embedded Software Engineer", department: "Electronics" },
          { rank: "member", name: "Rossella Mungiello", role: "Structural Engineer", department: "Structures" },
          { rank: "member", name: "Samuele Hayato Ishikawa", role: "Safety Officer", department: "Operations" },
          { rank: "member", name: "Sebastiano Tuccitto", role: "Design & Manufacturing Engineer", department: "Structures" },
          { rank: "member", name: "Simona Tauro", role: "Test & Mission Support Specialist", department: "Propulsion" },
          { rank: "member", name: "Stefano Motta", role: "Test Engineer", department: "Propulsion" },
          { rank: "member", name: "Tarik Nalcaci", role: "Propulsion Engineer", department: "Propulsion" },
          { rank: "member", name: "Tugberk Bardak", role: "Full Stack Developer", department: "Operations" },
          { rank: "member", name: "Valerio Donnini", role: "Hardware Engineer", department: "Electronics" },
          { rank: "member", name: "Vito Piazzolla", role: "Control Systems Engineer", department: "Controls and Systems" },
          { rank: "member", name: "Vukašin Kosijer", role: "Embedded Software Engineer", department: "Electronics" },
        ],
        advisors: [
          { name: "Prof. Alfonso Pagani", role: "Primary Faculty Advisor" },
          { name: "Prof. Enrico Zappino", role: "Faculty Advisor" },
          { name: "Fabio Meloni", role: "Founder & Senior Advisor" },
          { name: "Salvatore Lagrasta", role: "Avionics" },
          { name: "Cristian Manfredi", role: "Advisor" },
          { name: "Luca Loiodice", role: "Additive Manufacturing" },
          { name: "Francesca Bracaglia", role: "Finite Element Analysis" },
          { name: "Flora Punzi", role: "Senior FEA Analyst & Counselor" },
          { name: "Lorenzo Pezzolato", role: "Additive Manufacturing" },
          { name: "Matteo Postinghel", role: "Communication & Brand Strategy" },
          { name: "Edoardo Walter Bignami", role: "Communication & Brand Strategy" },
        ],
      },
      {
        kind: "groups",
        start: 2023,
        placeholder: true,
        groups: [
          { name: "Leadership", people: samples(3, 1) },
          { name: "Cavour", people: samples(6, 18) },
          { name: "Efesto", people: samples(7, 33) },
          { name: "Operations", people: samples(4, 4) },
        ],
      },
      {
        kind: "groups",
        start: 2022,
        groups: [
          {
            name: "Executive",
            people: [
              { name: "Fabio Meloni", role: "President" },
              { name: "Elena Dilorenzo", role: "Chief Operating Officer" },
              { name: "Luca Santoro", role: "Chief Technologist & Head of Strategy" },
            ],
          },
          {
            name: "Cavour",
            people: [
              { name: "Fabio Meloni", role: "Chief Engineer" },
              { name: "Andrea Pantano", role: "Mission Analyst · Safety and Launch Manager" },
              { name: "Edoardo Viglietti", role: "Finite Element Analysis Lead" },
              { name: "Luca Loiodice", role: "Design & Additive Manufacturing Lead" },
              { name: "Marco Prodan", role: "Recovery & Manufacturing Lead" },
              { name: "Mattia Saba", role: "Mission Analysis Lead" },
              { name: "Orlando Nardo", role: "Design & Additive Manufacturing Vice-lead" },
              { name: "Salvatore Lagrasta", role: "Avionics Lead" },
              { name: "Alessandro Nitti", role: "CFD Analyst" },
              { name: "Alex Aiello", role: "Avionics Engineer" },
              { name: "Andrea De Masi", role: "Software Engineer" },
              { name: "Andrea Ruscica", role: "Mechanical Engineer" },
              { name: "Anna Del Tin", role: "Hardware Engineer" },
              { name: "Eliza Ciszewska", role: "Mechanical Engineer" },
              { name: "Emir Topakci", role: "CAD & AM Engineer" },
              { name: "Federico Guglielmi", role: "Software Engineer" },
              { name: "Giacomo Luccisano", role: "Avionics Engineer" },
              { name: "Giuseppe Barbera", role: "Avionics Engineer" },
              { name: "Giuseppe Roccasalva", role: "Software Engineer" },
              { name: "Giusi Raso", role: "CFD Analyst" },
              { name: "Hassine El Ghazel", role: "Software Engineer" },
              { name: "Jacopo Cerzosimo", role: "Software Engineer" },
              { name: "Kacper Koncewicz", role: "Mechanical Engineer" },
              { name: "Mattia Angirillo", role: "FEM Analyst" },
              { name: "Michał Zawadzki", role: "CAD & AM Engineer" },
              { name: "Mohammad Yousefi", role: "FEM Analyst" },
              { name: "Mustafa Ulvi Aydin", role: "Mechanical Engineer" },
              { name: "Nikita Fusilli Grynchenko", role: "FEM Analyst" },
              { name: "Pierantonio Bertuccio", role: "FEM Analyst" },
              { name: "Riccardo Di Maria", role: "CFD Analyst" },
              { name: "Samuele Martello", role: "Avionics Engineer" },
              { name: "Tuna Sahin", role: "Mechanical Engineer" },
            ],
          },
          {
            name: "Efesto",
            people: [
              { name: "Matteo Crachi", role: "Chief Engineer" },
              { name: "Cristian Manfredi", role: "Liquid Propulsion Coordinator" },
              { name: "Daniele Boccacciari", role: "Liquid System Architecture Lead" },
              { name: "Gloria Nallo", role: "Thrust Chamber Assembly Lead" },
              { name: "Lorenzo Guarino", role: "Engine Cycle Lead" },
              { name: "Luca Barnobi", role: "Test Bench Lead" },
              { name: "Pier Luigi Mercadante", role: "Liquid Propulsion Coordinator" },
              { name: "Abdullah Çelik", role: "Propulsion Engineer" },
              { name: "Alessio Improta", role: "Propulsion Engineer" },
              { name: "Alex Jarod Sclafani", role: "Propulsion Engineer" },
              { name: "Alireza Khanzadeh", role: "Propulsion Engineer" },
              { name: "Areeb Ahmed", role: "Propulsion Engineer" },
              { name: "Cosmo Spinosa", role: "Propulsion Engineer" },
              { name: "Davide Parlato", role: "Propulsion Engineer" },
              { name: "Edoardo Baraldi", role: "Propulsion Engineer" },
              { name: "El Sheikh Isber Charbel Abdo", role: "Propulsion Engineer" },
              { name: "Ezgi Yenigun", role: "Propulsion Engineer" },
              { name: "Federica Carollo", role: "Propulsion Engineer" },
              { name: "Federica Pellegrini", role: "Propulsion Engineer" },
              { name: "Gabriele Caso", role: "Propulsion Engineer" },
              { name: "Giovanni Ferrannini", role: "Propulsion Engineer" },
              { name: "Guglielmo Iacono", role: "Propulsion Engineer" },
              { name: "Harrshit Oruganti Sridhar", role: "Propulsion Engineer" },
              { name: "Hojjat Miryavifard", role: "Propulsion Engineer" },
              { name: "Iftekhar Anwar", role: "Propulsion Engineer" },
              { name: "İlayda Deniz Bayraktar", role: "Propulsion Engineer" },
              { name: "Marco Guzzon", role: "Propulsion Engineer" },
              { name: "Marco Magnanini", role: "Propulsion Engineer" },
              { name: "Marco Romano Delogu", role: "Propulsion Engineer" },
              { name: "Margherita Michahelles", role: "Propulsion Engineer" },
              { name: "Michele Bordini", role: "Propulsion Engineer" },
              { name: "Michele Sannino", role: "Propulsion Engineer" },
              { name: "Oshani Kularathna", role: "Propulsion Engineer" },
              { name: "Pierluigi Petrachi", role: "Propulsion Engineer" },
              { name: "Riccardo Terzo", role: "Propulsion Engineer" },
              { name: "Suleyman Burak Deniz", role: "Propulsion Engineer" },
              { name: "Syed Muhammad Ussama Zafar", role: "Propulsion Engineer" },
            ],
          },
          {
            name: "Operations",
            people: [
              { name: "Alessandro Di Nuzzo", role: "Media Manager" },
              { name: "Andrea Pantano", role: "Logistics Manager" },
              { name: "Federica Portis", role: "Sponsoring · Safety and Launch Manager" },
              { name: "Federico Guglielmi", role: "IT Manager" },
              { name: "Matteo Manavello", role: "Sponsoring Manager" },
              { name: "Derin Yilmaz", role: "Outreach & Recognition" },
              { name: "Duru Duran", role: "Photographer" },
              { name: "Ettore Giuseppe De Bartolo", role: "Recruitment" },
              { name: "Gabriele Tanca", role: "Outreach & Recognition" },
              { name: "Hassine El Ghazel", role: "Software Engineer" },
              { name: "Maria Vittoria Giobbio", role: "Outreach & Recognition" },
              { name: "Obaid Ur Rehman", role: "Web Developer" },
              { name: "Pierluigi Petrachi", role: "Propulsion Engineer" },
              { name: "Wassim Cherkaoui", role: "Outreach & Recognition" },
              { name: "Yuri Valle", role: "Graphic Designer" },
            ],
          },
          {
            name: "Advisors",
            people: [
              { name: "Flora Punzi", role: "Senior FEA Analyst & Counselor" },
              { name: "Francesca Bracaglia", role: "FEA Advisor" },
              { name: "Gianluca Porta", role: "Advisor · Strategy" },
              { name: "Gregorio Torchia", role: "Advisor · Legal" },
              { name: "Mattia Trombini", role: "Advisor · Engineering" },
              { name: "Rebecca Masia", role: "Advisor · Engineering" },
            ],
          },
        ],
      },
      {
        kind: "groups",
        start: 2021,
        groups: [
          {
            name: "Operations",
            people: [
              { name: "Fabio Meloni", role: "President · Chief Engineer, Cavour" },
              { name: "Luca Santoro", role: "Chief Technologist & Head of Strategy" },
              { name: "Elena Dilorenzo", role: "Outreach & Recognition Coordinator" },
              { name: "Gregorio Torchia", role: "Legal Advisor" },
            ],
          },
          {
            name: "Avionics",
            people: [
              { name: "Salvatore Lagrasta", role: "Avionics Lead" },
              { name: "Giacomo Luccisano", role: "Avionics Engineer" },
              { name: "Federico Guglielmi", role: "Avionics Engineer & IT Manager" },
            ],
          },
          {
            name: "Liquid Propulsion",
            people: [
              { name: "Cristian Manfredi", role: "Propulsion Coordinator" },
              { name: "Pier Luigi Mercadante", role: "Propulsion Coordinator" },
            ],
          },
          {
            name: "Recovery & Mission Analysis",
            people: [
              { name: "Mattia Saba", role: "Lead Mission Analyst" },
              { name: "Andrea Ruscica", role: "Recovery Lead" },
              { name: "Andrea Troglia", role: "Recovery Lead" },
            ],
          },
          {
            name: "Aerostructures",
            people: [
              { name: "Francesca Bracaglia", role: "Aerostructures Lead" },
              { name: "Luca Loiodice", role: "CAD & Additive Manufacturing Lead" },
              { name: "Flora Punzi", role: "Senior FEA Analyst & Counselor" },
              { name: "Marco Prodan", role: "Manufacturing Specialist" },
              { name: "Edoardo Viglietti", role: "Structural Engineer & FEM Analyst" },
              { name: "Pierantonio Bertuccio", role: "FEM Analyst" },
              { name: "Mohammad Yousefi", role: "Structural Engineer" },
              { name: "Mustafa Ulvi Aydin", role: "Manufacturing Engineer" },
              { name: "Gianmatteo Migliore", role: "FEM Analyst" },
            ],
          },
        ],
      },
    ],
  },
};
