import type { TeamPage } from "./types";

// The Team page's data. Names, roles, divisions, LinkedIn handles, emails
// and stats come from the team's live page (politorocketteam.it/about/
// current-team, read 2026-10-07), with names trimmed and roles tidied ("Head
// of Propulsion Department" reads "Head of Propulsion"). A role the live data
// gives as "???" is left out. Photos were copied once into public/team/ from
// the URLs that page uses.

export const team: TeamPage = {
  description:
    "The students who design, build and fly PoliTo Rocket Team's rockets: who leads, every department, our advisors and every core member.",

  header: {
    eyebrow: "ABOUT · THE TEAM",
    title: "The Team",
    intro:
      "In the 2024–2025 academic year the Team has more than 150 undergraduate and graduate students. They come from almost every course at Politecnico di Torino, and from more than 30 countries.",
    stats: [
      { value: "150+", label: { text: "MEMBERS" } },
      { value: "30+", label: { text: "COUNTRIES" } },
      { value: "8", label: { text: "DEPARTMENTS", phone: "DEPTS" } },
      { value: "26%", label: { text: "INTERNATIONAL", phone: "INTL" } },
    ],
  },

  orgChart: {
    eyebrow: "WHO LEADS",
    title: "From the university to every department.",
    university: { name: "Politecnico di Torino", logo: "/team/polito-logo-white.svg" },
    leader: {
      name: "Andrea Pantano",
      role: "Team Leader",
      photo: "/team/andrea-pantano.jpg",
      linkedin: "andrea-pantano-84b805258",
      email: "president@politorocketteam.it",
    },
    leaders: [
      {
        name: "Andrea Manzo",
        role: "Chief Engineer",
        photo: "/team/andrea-manzo.jpg",
        linkedin: "andrea-manzo-b105612a4",
        email: "andrea.manzo@politorocketteam.it",
      },
      {
        name: "Riccardo Savio",
        role: "Project Manager",
        photo: "/team/riccardo-savio.jpg",
        linkedin: "riccardo-savio",
        email: "riccardo.savio@politorocketteam.it",
      },
      {
        name: "Rocco Bellon",
        role: "Head of Operations",
        linkedin: "rocco-bellon-0582772a9",
        email: "rocco.bellon@politorocketteam.it",
      },
      {
        name: "Marco Dona",
        role: "Head of R&D",
        photo: "/team/marco-dona.jpg",
        linkedin: "marco-dona1601",
        email: "marco.dona@politorocketteam.it",
      },
    ],
  },

  departments: {
    eyebrow: "DEPARTMENTS",
    title: "Departments",
    intro: "Every head, with the leads of their divisions.",
    groups: [
      {
        name: "Technical Departments",
        members: [
          {
            kind: "head",
            name: "Marco Delogu",
            role: "Head of Propulsion",
            photo: "/team/marco-delogu.jpg",
            linkedin: "marco-romano-delogu-637165225",
            email: "marco.delogu@politorocketteam.it",
            leads: [
              {
                name: "Samuele Lombardi",
                division: "Liquid System Architecture",
                photo: "/team/samuele-lombardi.jpg",
                linkedin: "samuele-lombardi-772935337",
              },
              {
                name: "Fabio Zeloni",
                division: "Thrust Chamber Assembly",
                photo: "/team/fabio-zeloni.jpg",
                linkedin: "fabiozeloni",
              },
            ],
          },
          {
            kind: "head",
            name: "Emir Topakci",
            role: "Head of Structures",
            photo: "/team/emir-topakci.jpg",
            linkedin: "emir-topakci-09a58420a",
            email: "emir.topakci@politorocketteam.it",
            leads: [
              {
                name: "Emir Topakci",
                division: "Design & Manufacturing",
                photo: "/team/emir-topakci.jpg",
                linkedin: "emir-topakci-09a58420a",
              },
              {
                name: "Emir Topakci",
                division: "Structures Analysis",
                photo: "/team/emir-topakci.jpg",
                linkedin: "emir-topakci-09a58420a",
              },
            ],
          },
          {
            kind: "head",
            name: "Alessandro Rabino",
            role: "Head of Aerodynamics",
            photo: "/team/alessandro-rabino.jpg",
            linkedin: "alessandro-rabino-568bb0276",
            email: "alessandro.rabino@politorocketteam.it",
            leads: [
              { name: "Maria Angelica Fullone Penna", division: "Mission Analysis" },
              { name: "Stefano Campagnolo", division: "Optimization and Analysis" },
            ],
          },
          {
            kind: "head",
            name: "Daniele Brero",
            role: "Head of Recovery",
            photo: "/team/daniele-brero.jpg",
            email: "daniele.brero@politorocketteam.it",
            leads: [
              { name: "Giovanni Tomasi", division: "Parachutes" },
              { name: "Ludovica Cassella", division: "Recovery Systems" },
            ],
          },
          {
            kind: "head",
            name: "Alessandro Giacobetti",
            role: "Head of Controls and Systems",
            photo: "/team/alessandro-giacobetti.jpg",
            linkedin: "alessandrogiacobetti",
            email: "alessandro.giacobetti@politorocketteam.it",
            leads: [
              { name: "Rocco Donnola", division: "Engine Control System", linkedin: "rocco-donnola" },
              {
                name: "Nicola Montagner",
                division: "Flight Control Systems",
                photo: "/team/nicola-montagner.jpg",
                linkedin: "nicola-montagner-b619a42b7",
              },
            ],
          },
          {
            kind: "head",
            name: "Michele Rossetto",
            role: "Head of Electronics",
            photo: "/team/michele-rossetto.jpg",
            linkedin: "michele-rossetto-06b1bb337",
            email: "michele.rossetto@politorocketteam.it",
            leads: [
              {
                name: "Giorgio Montese",
                division: "Firmware",
                photo: "/team/giorgio-montese.jpg",
                linkedin: "giorgio-montese",
              },
              {
                name: "Samuele Martello",
                division: "Ground Station",
                photo: "/team/samuele-martello.jpg",
                linkedin: "samuele-martello-633550277",
              },
              {
                name: "Arda Bildik",
                division: "Hardware",
                photo: "/team/arda-bildik.jpg",
                linkedin: "arda-bildik",
              },
            ],
          },
        ],
      },
      {
        name: "Operations",
        members: [
          {
            kind: "head",
            name: "Rocco Bellon",
            role: "Head of Operations",
            linkedin: "rocco-bellon-0582772a9",
            email: "rocco.bellon@politorocketteam.it",
            leads: [],
          },
          {
            kind: "division",
            name: "Luca Beccaria",
            division: "Communications",
            email: "luca.beccaria@politorocketteam.it",
          },
          {
            kind: "division",
            name: "Huseyin Gulec",
            division: "Information Technology",
            photo: "/team/huseyin-gulec.jpg",
            linkedin: "huseyingulec",
            email: "huseyin.gulec@politorocketteam.it",
          },
          {
            kind: "division",
            name: "Ettore De Bartolo",
            division: "Logistics",
            email: "ettore.debartolo@politorocketteam.it",
          },
          {
            kind: "division",
            name: "Asmaa Jamai",
            division: "Safety",
            linkedin: "asmaa-jamai-",
            email: "asmaa.jamai@politorocketteam.it",
          },
        ],
      },
    ],
  },

  advisors: {
    eyebrow: "ADVISORS",
    title: "The people who guide us.",
    intro: "Faculty of Politecnico and specialists who support the Team.",
    people: [
      {
        name: "Prof. Alfonso Pagani",
        role: "Primary Faculty Advisor",
        standing: "principal",
        photo: "/team/alfonso-pagani.jpg",
        linkedin: "alfonsopagani",
        email: "alfonso.pagani@polito.it",
      },
      {
        name: "Prof. Enrico Zappino",
        role: "Faculty Advisor",
        standing: "principal",
        photo: "/team/enrico-zappino.jpg",
        linkedin: "enrico-zappino-4a762326",
        email: "enrico.zappino@polito.it",
      },
      {
        name: "Fabio Meloni",
        role: "Founder & Senior Advisor",
        standing: "principal",
        photo: "/team/fabio-meloni.jpg",
        linkedin: "fabioski01",
        email: "fabio.meloni@politorocketteam.it",
      },
      {
        name: "Salvatore Lagrasta",
        role: "Avionics",
        standing: "specialist",
        photo: "/team/salvatore-lagrasta.jpg",
        linkedin: "salvatore-lagrasta",
        email: "salvatore.lagrasta@politorocketteam.it",
      },
      {
        name: "Cristian Manfredi",
        role: "Advisor",
        standing: "specialist",
        photo: "/team/cristian-manfredi.jpg",
        linkedin: "cristian-manfredi",
        email: "cristian.manfredi@politorocketteam.it",
      },
      {
        name: "Luca Loiodice",
        role: "Additive Manufacturing",
        standing: "specialist",
        photo: "/team/luca-loiodice.jpg",
        linkedin: "luca-loiodice-01l10",
        email: "luca.loiodice@politorocketteam.it",
      },
      {
        // The live LinkedIn link reads "francesca bracaglia", with a space,
        // which is no profile handle, so it is left out.
        name: "Francesca Bracaglia",
        role: "Finite Element Analysis",
        standing: "specialist",
        photo: "/team/francesca-bracaglia.jpg",
        email: "francesca.bracaglia@politorocketteam.it",
      },
      {
        name: "Flora Punzi",
        role: "Senior FEA Analyst & Counselor",
        standing: "specialist",
        photo: "/team/flora-punzi.jpg",
        linkedin: "fpunzi",
      },
      {
        name: "Lorenzo Pezzolato",
        role: "Additive Manufacturing",
        standing: "specialist",
        linkedin: "lorenzopezzolato",
      },
      {
        name: "Matteo Postinghel",
        role: "Communication & Brand Strategy",
        standing: "specialist",
        photo: "/team/matteo-postinghel.jpg",
        linkedin: "matteo-postinghel",
        email: "matteopostinghel@icloud.com",
      },
      {
        name: "Edoardo Walter Bignami",
        role: "Communication & Brand Strategy",
        standing: "specialist",
        photo: "/team/edoardo-walter-bignami.jpg",
        linkedin: "edoardo-bignami-68527920a",
        email: "edo.bigna@gmail.com",
      },
    ],
  },

  inNumbers: {
    eyebrow: "IN NUMBERS",
    title: "Who we are, by the numbers.",
    charts: [
      {
        title: "BY PROGRAM",
        slices: [
          { label: "Aerospace", percent: 59.7 },
          { label: "Mechanical", percent: 17.6 },
          { label: "Computer", percent: 6.7 },
          { label: "Electronic", percent: 5.9 },
          { label: "Management", percent: 3.4 },
          { label: "Other", percent: 6.7 },
        ],
      },
      {
        title: "BY LEVEL",
        slices: [
          { label: "Master's", percent: 50.4 },
          { label: "Bachelor's", percent: 48.8 },
          { label: "Ph.D.", percent: 0.8 },
        ],
      },
      {
        title: "BY ORIGIN",
        slices: [
          { label: "Domestic", percent: 73.8 },
          { label: "International", percent: 26.2 },
        ],
      },
    ],
  },

  coreMembers: {
    eyebrow: "CORE MEMBERS",
    title: "Everyone who builds it.",
    groupPhoto: { src: "/team/team-2022-06.jpg", alt: "The PoliTo Rocket Team on the steps of Politecnico di Torino" },
    // In alphabetical order, as the live page lists them. The live
    // "trk=p_" LinkedIn value is no profile handle, so it is left out.
    members: [
    { name: "Aamil Lodhi", role: "Design & Additive Manufacturing Engineer" },
    { name: "Alessandro Centorrino", role: "Aerodynamicist" },
    { name: "Alessandro Monti", role: "Propulsion Engineer" },
    { name: "Alessandro Rizzo", role: "Design & Manufacturing Engineer" },
    { name: "Alessandro Ruo Redda", role: "Propulsion Engineer", linkedin: "alessandro-ruo-redda" },
    { name: "Alessio Golini", role: "Hardware Engineer" },
    { name: "Alessio Nerjaku", role: "Mission Analyst" },
    { name: "Andrea Agostini", role: "Propulsion Engineer", linkedin: "andrea-agostini-" },
    { name: "Andrea Morra", role: "Ignition System Engineer" },
    { name: "Annamaria Gelesz", role: "Aerodynamicist", linkedin: "annamaria-gelesz" },
    { name: "Antonino Brandino", role: "Recovery Engineer" },
    { name: "Antonino Spadafora", role: "Propulsion Engineer", linkedin: "antonino-spadafora" },
    { name: "Antonino Gaetano Biondo", role: "Control Systems Engineer" },
    { name: "Antonio Sepe", role: "Propulsion Engineer", linkedin: "antonio-sepe" },
    { name: "Antonios Kakamoukas", role: "Structural Engineer", linkedin: "antonios-kakamoukas" },
    { name: "Asmaa Jamai", role: "Test & Mission Support · Safety", linkedin: "asmaa-jamai-" },
    { name: "Ata Akturk", role: "Hardware Engineer" },
    { name: "Aurelio Amato", role: "Mission Analyst" },
    { name: "Aysim Kukrek", role: "Recovery Engineer", linkedin: "aysim-kukrek" },
    { name: "Beatrice La Motta", role: "Test Engineer", linkedin: "beatrice-la-motta" },
    { name: "Carlo Paccagnella", role: "Hardware Engineer" },
    { name: "Carlo Ricciardi", role: "Design & Manufacturing Engineer", linkedin: "carlo-ricciardi" },
    { name: "Carlo Visalli", role: "Propulsion Engineer" },
    { name: "Chiara Balen", role: "Recovery Engineer", linkedin: "chiara-balen" },
    { name: "Claudia Sanna", role: "Desktop App Developer", linkedin: "claudia-sanna" },
    { name: "Cristian Manfredi", linkedin: "cristian-manfredi" },
    { name: "Cristiana Avati", role: "Ignition System Engineer" },
    { name: "Cristina Pecoriello", role: "Cryogenic System Engineer" },
    { name: "Daniele Padula", role: "Aerodynamicist" },
    { name: "Daniele Punzi", role: "Recovery Engineer", linkedin: "daniele-punzi" },
    { name: "Daniele Luigi Maresca", role: "Structural Engineer" },
    { name: "Dante Casaglia", role: "Structural Engineer", linkedin: "dante-casaglia" },
    { name: "Davide Adamo", role: "Aerodynamicist" },
    { name: "Davide Di Palmo", role: "Mission Analyst", linkedin: "davide-di-palmo-2a86a038b" },
    { name: "Dimitri Mazzone", role: "Test Engineer", linkedin: "dimitri-mazzone" },
    { name: "Eleonora Catozzo", role: "Propulsion Engineer" },
    { name: "Emma Chan", role: "Aerodynamicist", linkedin: "emma-chan-658537314" },
    { name: "Enes Göktepe", role: "Mission Analyst", linkedin: "enes-göktepe-281500239" },
    { name: "Federico Agricola", role: "Propulsion Engineer" },
    { name: "Federico Saviano", role: "Control Systems Engineer", linkedin: "federico-saviano" },
    { name: "Filippo Prosperi", role: "Test Engineer" },
    { name: "Filippo Pupo", role: "Structural Engineer" },
    { name: "Flavia Beatrice Anton", role: "Test & Mission Support Specialist" },
    { name: "Flavio Giglia", role: "Aerodynamicist" },
    { name: "Francesco Guerrini", role: "Sponsoring Specialist" },
    { name: "Francesco Gullo", role: "Recovery Engineer", linkedin: "francesco-gullo-" },
    { name: "Francesco Iannantuono", role: "Aerodynamicist" },
    { name: "Gabriel Avila", role: "Feed System Engineer" },
    { name: "Gabriele Angelillo", role: "Embedded Software Engineer" },
    { name: "Giacomo Bunino", role: "Control Systems Engineer" },
    { name: "Gianluca Marcato", role: "Design & Manufacturing Engineer" },
    { name: "Gianluca Marra", role: "Design & Manufacturing Engineer" },
    { name: "Gianluca Paolicelli", role: "RF Specialist" },
    { name: "Giovanni Tomasi", role: "Recovery Engineer", linkedin: "giovanni-tomasi" },
    { name: "Giuliana Matta", role: "Structural Engineer" },
    { name: "Harrshit Oruganti Sridhar", role: "Propulsion Engineer" },
    { name: "Ilhan Yilmaz Karadeniz", role: "Hardware Engineer", linkedin: "1lmaz-karadeniz" },
    { name: "İsmail Dündar", role: "Hardware Engineer", linkedin: "ismail-d" },
    { name: "Ismail Emre Karakutuk", role: "Hardware Engineer", linkedin: "ismail-emre-karak" },
    { name: "Jenny Rostaing", role: "Valves & Pipelines Engineer", linkedin: "jenny-rostaing-746500380" },
    { name: "Lorenzo Assiro", role: "Control Systems Engineer" },
    { name: "Lorenzo Scaravaglio", role: "Propulsion Engineer" },
    { name: "Luca Pagliei", role: "Propulsion Engineer" },
    { name: "Lucas De Jong", role: "Design & Manufacturing Engineer" },
    { name: "Lucio Ernesto Polci", role: "Propulsion Engineer" },
    { name: "Luigi Ruggieri", role: "Ignition System Engineer", linkedin: "luigi-ruggieri" },
    { name: "Luisa Barattin", role: "Aerodynamicist", linkedin: "luisa-barattin-" },
    { name: "Marco Mondin", role: "Sponsoring Specialist" },
    { name: "Margherita Boatto", role: "Test Engineer" },
    { name: "Maria Angelica Fullone Penna", role: "Mission Analyst" },
    { name: "Mariasole Martella", role: "Design & Manufacturing Engineer" },
    { name: "Martina Ginesi", role: "Aerodynamicist", linkedin: "martina-ginesi" },
    { name: "Matteo Petri", role: "Mechanical/Propulsion Engineer", linkedin: "matteo-petri" },
    { name: "Mattia Girotto", role: "Ignition System Engineer", linkedin: "mattia-girotto" },
    { name: "Mattia Sottile", role: "Structural Engineer" },
    { name: "Michelangelo Mangiapane", role: "Recovery Engineer", linkedin: "michelangelo-mangiapane" },
    { name: "Muhamamd Hamza Khan", role: "Embedded Software Engineer" },
    { name: "Mustafa Mert Yetim", role: "Hardware Engineer" },
    { name: "Mustafa Sezer Yilmaz", role: "Hardware Engineer" },
    { name: "Niccolò Faraci", role: "Design & Manufacturing Engineer", linkedin: "niccolò-faraci" },
    { name: "Nicolas Cerutti", role: "Software Engineer", linkedin: "nicolascerutti" },
    { name: "Nicolò Vetri", role: "Propulsion Engineer" },
    { name: "Panagiotis Dimitrios Argyris", role: "Propulsion Engineer" },
    { name: "Paul Teo Devis", role: "Electronics Engineer" },
    { name: "Pietro Isnardi", role: "Mission Analyst" },
    { name: "Ricardo Brunetti", role: "Structural Engineer", linkedin: "ricardo-brunetti" },
    { name: "Roberto Moro", role: "Structural Engineer", linkedin: "roberto-moro" },
    { name: "Rocco Maria Cherubini", role: "Mission Analyst" },
    { name: "Rosa Coppolino", role: "Structural Engineer" },
    { name: "Rosario Stramondo", role: "Embedded Software Engineer" },
    { name: "Rossella Mungiello", role: "Structural Engineer", linkedin: "rossella-mungiello" },
    { name: "Samuele Lombardi", role: "Propulsion Engineer" },
    { name: "Samuele Hayato Ishikawa", role: "Safety Officer" },
    { name: "Sebastiano Tuccitto", role: "Design & Manufacturing Engineer" },
    { name: "Simona Tauro", role: "Test & Mission Support Specialist" },
    { name: "Stefano Motta", role: "Test Engineer" },
    { name: "Tarik Nalcaci", role: "Propulsion Engineer" },
    { name: "Tugberk Bardak", role: "Full Stack Developer", linkedin: "tugberk-bardak" },
    { name: "Valerio Donnini", role: "Hardware Engineer", linkedin: "valerio-donnini-" },
    { name: "Vito Piazzolla", role: "Control Systems Engineer" },
    { name: "Vukašin Kosijer", role: "Embedded Software Engineer", linkedin: "kosijerv007" },
    ],
  },
};
