// A tiny inline preview of the group photo, so its frame paints at once while
// the photo loads. Made by scaling public/team/team-2022-06.jpg to 12px wide.
export const groupPhotoBlur =
  "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAGAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAeEAACAgMAAwEAAAAAAAAAAAABAgMEAAURBjFBUf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwCZa8kvHYXFSWSJY3YcRjzgJy7pNnZsUmMvJHSQqWdm6fR+EfuMYUJ7y//Z";
